server:
  port: 5002
spring:
  application:
    name: ms-yanki-transaction-validate-service
 # config:
  #  import: optional:configserver:http://ms-bank-config-server:8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
